# nmake makefile
#
# Tools used:
#  Compile::Watcom Resource Compiler
#  Compile::GNU C
#  Make: nmake or GNU make
all : Robots.exe

Robots.exe: robots.obj game.obj hiscores.obj robots.def robots.res
	gcc -Zomf robots.obj game.obj hiscores.obj robots.def -o Robots.exe
	wrc robots.res

robots.obj: robots.c control.h
	gcc -Wall -Zomf -c -O2 robots.c -o robots.obj

game.obj : game.c
	gcc -Wall -Zomf -c -O2 game.c -o game.obj

hiscores.obj : hiscores.c
	gcc -Wall -Zomf -c -O2 hiscores.c -o hiscores.obj

robots.res : robots.rc robots.ico 
	wrc -r robots.rc

clean :
	rm -rf *exe *RES *obj